rules <- tibble::tribble(
  ~priority, ~type,  ~tokens, ~pattern, ~canonical,
  # --- Bedrijven
  1, "ALL",  list(c("4wi1ho")), NA, "Coöperatieve Vereniging 4Wi1Ho U.A.",
  1, "ALL",  list(c("RWTH")), NA, "RHEINISCH-WESTFAELISCHE TECHNISCHE HOCHSCHULE (RWTH)",
  1, "ALL",  list(c("TECHNISCHE", "HOCHSCHULE", "AACHEN")), NA, "RHEINISCH-WESTFAELISCHE TECHNISCHE HOCHSCHULE (RWTH)",
  1, "ALL",  list(c("COSUN")), NA, "KONINKLIJKE COOEPERATIE COSUN",
  1, "ALL",  list(c("GLAXOSMITHKLINE")), NA, "GLAXOSMITHKLINE BIOLOGAL",
  1, "ALL",  list(c("3B", "FUNDUS.*")), NA, "3B FUNDUS",
  1, "ALL",  list(c("2-B ENERGY")), NA, "2-B ENERGY",
  1, "ALL",  list(c("DSM ")), NA, "DSM SINOCHEM PHARM NL",
  1, "ALL",  list(c("TYCO")), NA, "Tyco electronics",
  3, "ALL",  list(c("philips|signify|filips koninklejke")), NA, "Signify N.V.",
  1, "ALL",  list(c("asml|asmlnetherlands")), NA, "ASML Netherlands B.V.",
  1, "ALL",  list(c("\\bnxp\\b")), NA, "NXP B.V.",
  1, "ALL",  list(c("dolby")), NA, "Dolby Global B.V.",
  1, "ALL",  list(c("unilever")), NA, "Unilever Nederland",
  1, "ALL",  list(c("sappi")), NA, "Sappi Biochemtech B.V.",
  1, "ALL",  list(c("anteryon")), NA, "Anteryon B.V.",
  1, "ALL",  list(c("4Silence")), NA, "4Silence B.V.",
  1, "ALL",  list(c("4d pharma")), NA, "4d pharma",
  1, "ALL",  list(c("zytec")), NA, "zytec",
  1, "ALL",  list(c("enza", "zaden")), NA, "Enza Zaden",
  1, "ALL",  list(c("verschoor", "horticulture")), NA, "A. Verschoor Horticulture Import-Export B.V.",
  1, "ALL",  list(c("AbGenomics.*")), NA, "AbGenomics B.V.",
  1, "ALL",  list(c("aduro", "biotech")), NA, "Aduro Biotech, Europe B.V.",
  1, "ALL",  list(c("adv.*", "tail", "oil")), NA, "Advanced Tail-end Oil Company (ATOL) N.V.",
  1, "ALL",  list(c("aeg", "power|pauer")), NA, "AEG Power Solutions B.V.",
  1, "ALL",  list(c("aerospace", "prop.*", "prod.*")), NA, "Aerospace Propulsion Products (A. P.P.) B.V.",
  1, "ALL",  list(c("kademish zikenkhojs lejden kh o d n lyumk")), NA, "Academisch Ziekenhuis Leiden",
  1, "ALL",  list(c("aktso|akzo|akxo", "nobel.*|novel.*")), NA, "AKZO Nobel Nederland B.V.",
  1, "ALL",  list(c("akzonobel")), NA, "AKZO Nobel Nederland B.V.",
  1, "ALL",  list(c("anteverta")), NA, "Anteverta-mw B.V.",
  1, "ALL",  list(c("amst.*", "mole.*", "thera.*")), NA, "Amsterdam Molecular Therapeutics (AMT) Holding N.V.",
  1, "ALL",  list(c("Apex")), NA, "Apex Europe B.V.",
  1, "ALL",  list(c("schlumberger")), NA, "Schlumberger B.V.",
  1, "ALL",  list(c("alstom")), NA, "Alstom Renewable Energies",
  1, "ALL",  list(c("scafom")), NA, "Scafom International B.V.",
  1, "ALL",  list(c("Scarabee", "syst", "tech")), NA, "Scarabee Systems & Technology B.V.",
  1, "ALL",  list(c("Scarabee", "id")), NA, "Scarabee ID B.V",
  1, "ALL",  list(c("irdeto")), NA, "Irdeto B.V.",
  1, "ALL",  list(c("2m", "Eng.*")), NA, "2M Engineering Limited",
  1, "ALL",  list(c("2", "Getthere")), NA, "2 Getthere B.V.",
  1, "ALL",  list(c("\\bshell\\b")), NA, "ROYAL DUTCH SHELL plc",
  1, "ALL",  list(c("albemarle")), NA, "Ketjen Netherlands B.V",
  1, "ALL",  list(c("alcomex")), NA, "Ketjen Netherlands B.V",
  1, "ALL",  list(c("hgst")), NA, "HGST Netherlands B.V.",
  1, "ALL",  list(c("akzo","nobel|novel")), NA, "AKZO Nobel Decorative Coatings",
  1, "ALL",  list(c("dow global")), NA, "Dow Global Holdings Netherlands B.V.",
  1, "ALL",  list(c("\\bkpn\\b")), NA, "kpn",
  1, "ALL",  list(c("qualcomm")), NA, "Qualcomm Technologies Netherlands B.V.",
  1, "ALL",  list(c("\\basm\\b")), NA, "asm",
  1, "ALL",  list(c("\\ford\\b")), NA, "Ford Nederland B.V.",
  1, "ALL",  list(c("\\sabic\\b")), NA, "SABIC Europe B.V.",
  1, "ALL",  list(c("\\sara lee\\b")), NA, "SARA LEE INTERNATIONAL B.V.",
  1, "ALL",  list(c("sara", "lee")), NA, "SARA LEE INTERNATIONAL B.V.",
  1, "ALL",  list(c("douwe", "egberts")), NA, "SARA LEE INTERNATIONAL B.V.",
  1, "ALL",  list(c("\\samsung\\b")), NA, "Samsung SDS Global SCL Netherlands Coöperatief U.A.",
  1, "ALL",  list(c("\\siemens\\b")), NA, "Siemens Industry Software Netherlands B.V.",
  1, "ALL",  list(c("\\bayer\\b")), NA, "Bayer Netherlands B.V.",
  1, "ALL",  list(c("\\tomtom\\b")), NA, "TomTom N.V.",
  1, "ALL",  list(c("\\zeiss\\b", "\\bcarl\\b")), NA, "Carl Zeiss B.V.",
  1, "ALL",  list(c("\\bitrec\\b")), NA, "Itrec B.V.",
  1, "ALL",  list(c("\\nexperia\\b")), NA, "Nexperia B.V.",
  1, "ALL",  list(c("\\stmicroelectronics\\b|st microelectronics")), NA, "STMicroelectronics N.V.",
  1, "ALL",  list(c("\\imec\\b")), NA, "IMEC-NL",
  1, "ALL",  list(c("\\heineken\\b")), NA, "Heineken N.V.",
  2, "ALL",  list(c("10x genomics")), NA, "10X Genomics B.V.",
  2, "ALL",  list(c("\\bbosch\\b")), NA, "Robert Bosch Holding Nederland B.V.",
  2, "ALL",  list(c("mitsubishi")), NA, "Mitsubishi Nederland B.V.",
  2, "ALL",  list(c("microsoft")), NA, "Microsoft B.V. ",
  2, "ALL",  list(c("janssen", "pharma|pharmaceuticals")), NA, "janssen & janssen",
  2, "ALL",  list(c("syngenta")), NA, "Syngenta Alpha B.V.",
  2, "ALL",  list(c("fujifilm")), NA, "FUJIFILM Europe B.V.",
  2, "ALL",  list(c("broadcom")), NA, "Broadcom Netherlands B.V.",
  2, "ALL",  list(c("ericsson")), NA, "Ericsson Telecommunicatie B.V.",
  2, "ALL",  list(c("stericsson")), NA, "Ericsson Telecommunicatie B.V.",
  2, "ALL",  list(c("lely","patent")), NA, "Lely Patent N.V.",
  2, "ALL",  list(c("^abb ")), NA, "ABB B.V.",
  2, "ALL",  list(c("^abb ","mobility")), NA, "ABB E-mobility B.V.",
  2, "ALL",  list(c("sabic|saudi basic")), NA, "SABIC GLOBAL TECHNOLOGIES B.V.",
  2, "ALL",  list(c("COMMSCOPE")), NA, "CommScope Netherlands B.V.",
  2, "ALL",  list(c("HUAWEI")), NA, "Huawei",
  2, "ALL",  list(c("^ams ")), NA, "AMS",
  2, "ALL",  list(c("zytec")), NA, "Zytec B.V.",
  2, "ALL",  list(c("2b|2 b", "energy")), NA, "Energy 2B",
  2, "ALL",  list(c("4c", "care")), NA, "4C Care & Technology B.V.",
  2, "ALL",  list(c("topchiev")), NA, "A.V. Topchiev Institute of Petrochemical Synthesis (TIPS)",
  2, "ALL",  list(c("travix")), NA, "travix international b.v",
  2, "ALL",  list(c("\\bdsm\\b","inno.*")), NA, "dsm innovative",
  2, "ALL",  list(c("\\bbank\\b","nederl.*")), NA, "de nederlandse bank",
  2, "ALL",  list(c("\\bwetsus\\b")), NA, "Wetsus, European Centre of Excellence for Sustainable Water Technology",
  2, "ALL",  list(c("\\bHeeren\\b", "\\bloo\\b")), NA, "'s Heeren Loo",
  2, "ALL",  list(c("\\bnutricia\\b")), NA, "Nutricia Research Foundation",
  2, "ALL",  list(c("\\babbott\\b")), NA, "abbott healthcare",
  2, "ALL",  list(c("\\babl\\b", "herbarium")), NA, "abl herbarium",
  2, "ALL",  list(c("\\babn\\b", "amro")), NA, "abn amro bank",
  2, "ALL",  list(c("\\bacacia\\b", "water")), NA, "acacia water",
  2, "ALL",  list(c("acad.*", "coll.*","center|centre|ct","health", "limburg")), NA, "academic collaborative center for public health limburg",
  2, "ALL",  list(c("accare")), NA, "accare",
  2, "ALL",  list(c("accsysacerta", "pharm.*")), NA, "accsysacerta",
  2, "ALL",  list(c("achmea")), NA, "achmea",
  2, "ALL",  list(c("aerovision")), NA, "aerovision b.v.",
  2, "ALL",  list(c("advisium")), NA, "advisium",
  2, "ALL",  list(c("aeon", "astron")), NA, "aeon astron europe b.v",
  1, "ALL",  list(c("2-bbb", "medicines" )), NA, "2-BBB Medicines B.V.",
  1, "ALL",  list(c("20med" )), NA, "20 medtherapeutics b.v.",
  1, "ALL",  list(c("2getthere")), NA, "2getthere b.v.",
  1, "ALL",  list(c("pharmxchange")), NA, "3d-pharmxchange",
  1, "ALL",  list(c("4dgeo")), NA, "4dgeo",
  1, "ALL",  list(c("3duniversum")), NA, "3duniversum",
  1, "ALL",  list(c("510", "initiative")), NA, "510 an initiative from the Dutch Red Cross",
  1, "ALL",  list(c("904", "labs")), NA, "904Labs B.V.",
  1, "ALL",  list(c("a-skin")), NA, "a-skin nederland b.v.",
  1, "ALL",  list(c("kpmg")), NA, "kpmg",
  1, "ALL",  list(c("netspar")), NA, "netspar",
  # Instituten
  1, "ALL",  list(c("nederlandse organisatie voor toegepastnatuurwetenschappelijk onderzoek tno")), NA, "nederlandse organisatie voor toegepastnatuurwetenschappelijk onderzoek - tno",
  1, "ALL",  list(c("nederlands.*","organisatie","toegepast|natuurwetenschap")), NA, "nederlandse organisatie voor toegepastnatuurwetenschappelijk onderzoek - tno",
  1, "ALL",  list(c("netherlands*","organization","applied", "research")), NA, "nederlandse organisatie voor toegepastnatuurwetenschappelijk onderzoek - tno",
  1, "ALL",  list(c("tno")), NA, "nederlandse organisatie voor toegepastnatuurwetenschappelijk onderzoek - tno",
  1, "ALL",  list(c("netherland.*", "org.*", "applied", "scien.*", "res")), NA, "nederlandse organisatie voor toegepastnatuurwetenschappelijk onderzoek - tno",
  1, "ALL",  list(c(" nioo")), NA, "nederlands instituut voor ecologie - nioo",
  1, "ALL",  list(c("nederlands", "instituut|inst", "ecologie")), NA, "nederlands instituut voor ecologie - nioo",
  1, "ALL",  list(c("stichting", "nederlands|nedrlands", "kanker")), NA, "  stichting het nederlands kanker instituut",
  1, "ALL",  list(c("rijks", "volksgezondheid", "milieu")), NA, "Rijksinstituut voor Volksgezondheid en Milieu (RIVM)",
  1, "ALL",  list(c("deltares")), NA, "deltares",
  1, "ALL",  list(c("int.*","inst.*","social","history")), NA, "international institute of social history",
  1, "ALL",  list(c("irewoc")), NA, "international research on working children",
  1, "ALL",  list(c("int.*", "res.*", "work.*", "child*")), NA, "international research on working children",
  1, "ALL",  list(c("planck", "max", "psych.*")), NA, "max planck institute for psycholinguistics",
  1, "ALL",  list(c("hubrecht")), NA, "Hubrecht Institute for Developmental Biology and Stem Cell Research",
  1, "ALL",  list(c("copernicus","sustain.*")), NA, "utrecht university",
  1, "ALL",  list(c("artemis","health")), NA, "artemis one health",
  1, "ALL",  list(c("\\bnivel\\b")), NA, "Netherlands Institute for Health Services Research",
  1, "ALL",  list(c("nioo-knaw|nioo")), NA, "Netherlands Institute of Ecology",
  1, "ALL",  list(c("neth.*", "inst.*", "eco.*")), NA, "Netherlands Institute of Ecology",
  1, "ALL",  list(c("nin-knaw|\\bnin\\b")), NA, "netherlands institute for neuroscience",
  1, "ALL",  list(c("Nederlands", "Herseninstituut")), NA, "netherlands institute for neuroscience",
  3, "ALL",  list(c("nat.*", "inst.*", "nut.*")), NA, "National Institute of Nutrition",
  1, "ALL",  list(c("meertens")), NA, "Meertens Institute",
  1, "ALL",  list(c("cbs-knaw")), NA, "Westerdijk Insitute",
  1, "ALL",  list(c("\\bWesterdijk\\b")), NA, "Westerdijk Insitute",
  1, "ALL",  list(c("cent.*", "stat.*")), NA, "Centraal Bureau voor de Statistiek",
  1, "ALL",  list(c("statistics", "netherlands")), NA, "Centraal Bureau voor de Statistiek",
  1, "ALL",  list(c("\\bcbs\\b")), NA, "Centraal Bureau voor de Statistiek",
  1, "ALL",  list(c("\\btransfore\\b")), NA, "transfore",
  1, "ALL",  list(c("inst.*", "water", "edu.*")), NA, "IHE Delft Institute for Water Education",
  1, "ALL",  list(c("\\bihe\\b")), NA, "IHE Delft Institute for Water Education",
  1, "ALL",  list(c("hoff", "inst.*")), NA, "Van 't Hoff Institute for Molecular Sciences",
  1, "ANY",  list(c("\\bggz\\b","altrecht", "\\blentis\\b", "\\brivierduinen\\b", "\\b\\ingeest\\b")), NA, "GGZ",
  1, "ALL",  list(c("hoff", "inst.*")), NA, "Van 't Hoff Institute for Molecular Sciences",
  1, "ALL",  list(c("inst.*", "social", "studies", "hague|haag")), NA, "International Institute of Social Studies",
  1, "ALL",  list(c("dutch", "poly.*", "inst.*")), NA, "Dutch Polymer Institute",
  1, "ALL",  list(c("vitalis")), NA, "Vitalis WoonZorg Group",
  1, "ALL",  list(c("holst", "\\bct\\b|centre|center")), NA, "Holst Centre",
  1, "ALL",  list(c("\\bamolf\\b")), NA, "Institute for Atomic and Molecular Physics",
  1, "ALL",  list(c("inst.*", "atom.*", "phys.*", "mol.*")), NA, "Institute for Atomic and Molecular Physics",
  1, "ALL",  list(c("(cwi)")), NA, "centrum wiskunde and informatica (cwi)",
  1, "ALL",  list(c("cen.*|\\bct\\b", "wiskunde|math.*", "infor.*")), NA, "centrum wiskunde and informatica (cwi)",
  1, "ALL",  list(c("rivm")), NA, "national institute for public health and the environment",
  1, "ALL",  list(c("nat.*", "inst.*","public", "health")), NA, "national institute for public health and the environment",
  1, "ALL",  list(c("knmi")), NA, "Royal Netherlands Meteorological Institute",
  1, "ALL",  list(c("royal", "inst.*", "meteo.*")), NA, "Royal Netherlands Meteorological Institute",
  1, "ALL",  list(c("\\bnioz\\b")), NA, "Royal Netherlands Institute for Sea Research",
  1, "ALL",  list(c("royal", "inst.*", "sea", "res.*")), NA, "Royal Netherlands Institute for Sea Research",
  1, "ALL",  list(c("zernike", "inst.*", "sea", "res.*")), NA, "zernike institute of advanced materials",
  1, "ALL",  list(c("\\bestec\\b")), NA, "European Space Research and Technology Centre",
  1, "ALL",  list(c("euro.*", "space", "res.*", "ct|cen.*")), NA, "European Space Research and Technology Centre",
  1, "ALL",  list(c("incas3")), NA, "incas3",
  1, "ALL",  list(c("\\bPBL\\b|^PBL |(PBL)")), NA, "netherlands environmental assessment agency",
  1, "ALL",  list(c("Netherlands", "environmen.*", "assess.*", "agenc.*")), NA, "netherlands environmental assessment agency",
  1, "ALL",  list(c("syntecnos")), NA, "syntecnos b.v.",
  1, "ALL",  list(c("waternet")), NA, "waternet",
  1, "ALL",  list(c("tetra", "pak")), NA, "tetra pak",
  1, "ALL",  list(c("\\bkwr\\b")), NA, "watercycle research institute",
  1, "ALL",  list(c("water", "cycle", "research")), NA, "watercycle research institute",
  1, "ALL",  list(c("\\bartez\\b")), NA, "artez institute of the arts",
  1, "ALL",  list(c("artez","kunst.*|art.*")), NA, "artez institute of the arts",
  1, "ALL",  list(c("artez","insti.*|hoge.*|univ.*")), NA, "artez institute of the arts",
  1, "ALL",  list(c("\\bti\\b|top institute", "food", "nutrition")), NA, "Universitair Medisch Centrum Groningen (UMCG)",
  1, "ALL",  list(c("euro.*", "space","agenc.*" )), NA, "european space agency",
  1, "ALL",  list(c("esa-estec" )), NA, "European Space Research and Technology Centre",
  1, "ALL",  list(c("neth.*","inst.*", "space", "res.*" )), NA, "netherlands institute for space research",
  1, "ALL",  list(c("space*", "res.*", "org.*", "neth.*" )), NA, "netherlands institute for space research",
  1, "ALL",  list(c("\\bSRON\\b" )), NA, "netherlands institute for space research",
  1, "ALL",  list(c("\\barcnl\b" )), NA, "advanced research center for nanolithography",
  1, "ALL",  list(c("adv.*", "nano.*", "res.*" )), NA, "advanced research center for nanolithography",
  1, "ALL",  list(c("inst.*", "env.*", "science.*" )), NA, "institute of environmental sciences",
  1, "ALL",  list(c("inst.*", "milieu.*", "weten.*" )), NA, "institute of environmental sciences",
  1, "ALL",  list(c("\\bcml\\b|(cml)" )), NA, "institute of environmental sciences",
  1, "ALL",  list(c("113", "suicide|zelfmoord" )), NA, "113 zelfmoordpreventie",
  1, "ALL",  list(c("aachen", "inst.*", "biobased", "mat.*")), NA, "aachen-maastricht institute for biobased materials",
  1, "ALL",  list(c("Afri.*", "Stud.*", "Centr.*")), NA, "African Studies Centre",
  1, "ALL",  list(c("agri.*", "eco.*", "inst.*")), NA, "agricultural economics institute wageningen",
  1, "ALL",  list(c("agrifirm", "inno.*", "center|ct|centre")), NA, "agrifirm innovation center",
  1, "ALL",  list(c("\\balan\\b", "\\bturing\\b", "inst.*")), NA, "alan turing institute",
  1, "ALL",  list(c("neth.*|ned.*", "inst.*|centrum", "stud.*", "crim.*", "law|recht")), NA, "netherlands institute for the study of crime and law enforcement",
  1, "ALL",  list(c("\\bncsr\\b")), NA, "netherlands institute for the study of crime and law enforcement",
  1, "ALL",  list(c("\\btrimbos\\b")), NA, "Trimbos institute",
  1, "ALL",  list(c("uni.*", "cardio.*", "institute")), NA, "interuniversity cardiology institute",
  1, "ALL",  list(c("acad.*", "werkplaats", "risico")), NA, "academische werkplaats risicojeugd/intermetzo",
  1, "ALL",  list(c("\\bacerta\\b")), NA, "acerta pharma",
  1, "ALL",  list(c("\\bacibadem\\b")), NA, "acibadem international medical center",
  1, "ALL",  list(c("\\bagendia\\b")), NA, "agendia",
  1, "ALL",  list(c("\\bahold\\b")), NA, "ahold delhaize",
  1, "ALL",  list(c("\\baimm\\b")), NA, "aimm therapeutics",
  1, "ALL",  list(c("\\baios\\b")), NA, "aios",
  1, "ALL",  list(c("\\bairbus\\b", "defence", "space")), NA, "Airbus defence and Space",
  1, "ALL",  list(c("\\baktis\\b", "hydraulics")), NA, "aktis hydraulics",
  1, "ALL",  list(c("\\balbert\\b", "schweitzer", "ziek.*|hos.*|medi.*")), NA, "albert schweitzer ziekenhuis",
  1, "ALL",  list(c("allander")), NA, "allander",
  1, "ALL",  list(c("alseas")), NA, "alseas",
  1, "ALL",  list(c("\\bamnitrans\\b", "eye")), NA, "amnitrans eye bank",
  1, "ALL",  list(c("ampleon")), NA, "ampleon",
  1, "ALL",  list(c("stichting", "epile.*", "instelli.*")), NA, "Stiching Epilepsie Instellingen",
  1, "ALL",  list(c("gastroenterology", "amsterdam", "endo.*")), NA, "amsterdam gastroenterology endocrinology & metabolism",
  1, "ALL",  list(c("amsterdam", "institute", "global", "health")), NA, "amsterdam institute for global health and development",
  1, "ALL",  list(c("amsterdam", "collaboration", "sport.*", "health")), NA, "amsterdam collaboration for health and safety in sports",
  1, "ALL",  list(c("thermo", "fisher")), NA, "thermo fisher scientific",
  1, "ALL",  list(c("wageningen", "food", "biobased|bio-based")), NA, "wageningen food and biobased research",
  1, "ALL",  list(c("reinier", "\\barkel\\b")), NA, "reinier van arkel mental health institute",
  1, "ALL",  list(c("\\btop\\b", "\\bsector\\b", "health")), NA, "Top sector life sciences & health",
  1, "ALL",  list(c("\\broyal\\b", "\\bhaskoning\\b", "health")), NA, "royal haskoning dhv",
  #  2. Unis en UMC
  #  2.1 Amsterdam
  1, "ALL",  list(c("amsterdam","umc|medical","center|centre","vu|vrije")),                     NA,       "vrije universiteit medical center",
  2, "ALL",  list(c("amsterdam","uni.*")),                     NA,       "universiteit van amsterdam",
  2, "ALL",  list(c("vumc.*")),                     NA,       "vrije universiteit medical center",
  1, "ALL",  list(c("acad.*","medi.*","center|centre","vrije","vu|amsterdam")),                     NA,       "vrije universiteit medical center",
  1, "ALL",  list(c("acad.*","medi.*","center|centre","amsterdam")),                     NA,       "Amsterdam University Medical Centers",
  1, "ALL",  list(c("vu","umc|medical","center|centre")),                     NA,       "vrije universiteit medical center",
  1, "ALL",  list(c("vu","university","umc|medical","center|centre")),                     NA,       "vrije universiteit medical center",
  1, "ALL",  list(c("vu medical center")),                     NA,       "vrije universiteit medical center",
  1, "ALL",  list(c("acad.*", "child.*", "ado.*", "psy.*")),                     NA,       "Amsterdam University Medical Centers",
  1, "ALL",  list(c("amsterdam","umc","uva|universiteit van amsterdam|amc")), NA, "Amsterdam University Medical Centers",
  2, "ALL",  list(c("amsterdam","umc")), NA, "Amsterdam University Medical Centers",
  2, "ALL",  list(c("amsterdam|uni.*","vrij.*|\\bvu\\b")),                     NA,       "Vrije Universiteit Amsterdam",
  #  2.2 Utrecht
  2, "ALL",  list(c("utrecht", "med.*", "ct")), NA, "Universitair Medisch Centrum Utrecht",
  2, "ALL",  list(c("umc", "utrecht")), NA, "Universitair Medisch Centrum Utrecht",
  2, "ALL",  list(c("utrecht", "univ.*")), NA, "Utrecht University",
  #  2.3 Eindhoven
  2, "ALL",  list(c("TU/E |tu eindhoven")), NA, "Technische universiteit eindhoven",
  2, "ALL",  list(c("Technische|\\b\tu\b", "eindhoven")), NA, "Technische universiteit eindhoven",
  2, "ALL",  list(c("univ.*", "eindhoven", "tech.*")), NA, "Technische universiteit eindhoven",
  2, "ALL",  list(c("$tue")), NA, "Technische universiteit eindhoven",
  2, "ALL",  list(c("\\btu\\b", "\\beindhoven\\b")), NA, "Technische universiteit eindhoven",
  #  2.3 Delft
  2, "ALL",  list(c("Technische|technical", "univ.*", "delft")), NA, "Technische universiteit delft",
  2, "ALL",  list(c("TU", "delft")), NA, "Technische universiteit delft",
  2, "ALL",  list(c("univ.*", "delft")), NA, "Technische universiteit delft",
  # 2.4 Leiden
  1, "ALL",  list(c("acad.*", "zieken.*|zienken.*|zeikenhuis|hospi.*", "leiden")), NA, "Academisch Ziekenhuis Leiden",
  1, "ALL",  list(c("acad.*", "zieken.*", "leiden")), NA, "Academisch Ziekenhuis Leiden",
  1, "ALL",  list(c("univ.*", "medical.*", "leiden")), NA, "Academisch Ziekenhuis Leiden",
  1, "ALL",  list(c("umc", "leiden")), NA, "Academisch Ziekenhuis Leiden",
  1, "ALL",  list(c("lumc")), NA, "Academisch Ziekenhuis Leiden",
  1, "ALL",  list(c("leiden", "univ.*")), NA, "Leiden University",
  # 2.5 Rotterdam
  1, "ALL",  list(c("erasmus", "univ.*", "rotterdam", "med.*")), NA, "Erasmus Universitair Medisch Centrum Rotterdam (Erasmus MC)",
  1, "ALL",  list(c("erasmus", "umc|med.*|\\bmc\\b")), NA, "Erasmus Universitair Medisch Centrum Rotterdam (Erasmus MC)",
  1, "ALL",  list(c("rotterdam", "umc")), NA, "Erasmus Universitair Medisch Centrum Rotterdam (Erasmus MC)",
  2, "ALL",  list(c("erasmus", "univ.*")), NA, "Erasmus University",
  2, "ALL",  list(c("rotterdam", "univ.*")), NA, "Erasmus University",
  2, "ALL",  list(c("erasmusmc")), NA, "Erasmus Universitair Medisch Centrum Rotterdam (Erasmus MC)",
  # 2.6 Groningen
  1, "ALL",  list(c("acad.*", "ziek.*", "groningen")), NA, "Universitair Medisch Centrum Groningen (UMCG)",
  1, "ALL",  list(c("umc", "groningen")), NA, "Universitair Medisch Centrum Groningen (UMCG)",
  1, "ALL",  list(c("umcg")), NA, "Universitair Medisch Centrum Groningen (UMCG)",
  1, "ALL",  list(c("univ.*", "medi.*","groningen")), NA, "Universitair Medisch Centrum Groningen (UMCG)",
  2, "ALL",  list(c("groningen", "rijksuniv.*")), NA, "University of Groningen",
  2, "ALL",  list(c("groningen", "univ.*")), NA, "University of Groningen",
  # 2.7 Maastricht
  1, "ALL",  list(c("acad.*|uni.*", "ziek.*|medi.*", "maastricht")), NA, "Maastricht UMC-Holding B.V.",
  1, "ALL",  list(c("maastricht", "umc")), NA, "Maastricht UMC-Holding B.V.",
  2, "ALL",  list(c("maastricht", "univ.*")), NA, "Universiteit Maastricht",
  2, "ALL",  list(c("maastrichtuniversity")), NA, "Universiteit Maastricht",
  2, "ALL",  list(c("\\bmumc\\b")), NA, "Maastricht UMC-Holding B.V.",

  # 2.8 Nijmegen
  1, "ALL",  list(c("acad.*|uni.*|radboud", "ziek.*|medi.*|hospital|umc", "nijmegen")), NA, "Stichting Radboud universitair medisch centrum",
  2, "ALL",  list(c("radboud|nijmegen", "univ.*")), NA, "Radboud Universiteit Nijmegen",
  2, "ALL",  list(c("radboudumc")), NA, "Stichting Radboud universitair medisch centrum",
  # 2.9 Twente
  2, "ALL",  list(c("twente", "univ.*")), NA, "Universiteit Twente",
  # 2.10 Tilburg
  2, "ALL",  list(c("tilburg", "univ.*")), NA, "Stichting Katholieke Universiteit Brabant",
  # 2.11 Wageningen
  2, "ALL",  list(c("wageningen", "univ.*")), NA, "Wageningen University & Research",
  2, "ALL",  list(c("stichting", "wageningen", "res.*")), NA, "Wageningen University & Research",
  2, "ALL",  list(c("alterra")), NA, "Wageningen Environmental Research",
  # 3. Ziekenhuizen
  2, "ALL",  list(c("ruyter", "ziek.*|hosp.*")), NA, "admiraal de ruyter ziekenhuis",
  2, "ALL",  list(c("adrz")), NA, "admiraal de ruyter ziekenhuis",
  2, "ALL",  list(c("\\bAtrium\\b")), NA, "Atrium Medisch Centrum Parkstad",
  2, "ALL",  list(c("\\bMeander\\b")), NA, "Meander Medisch Centrum Parkstad",
  2,  "ALL", list(c("maastricht", "umc\\+|umc|universit.*med.*|centrum|mc|med.*|centrum|ziek.*|hosp.*")), NA, "maastricht umc+",
  2, "ALL", list(c("\\bisala\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "isala ziekenhuis",
  2, "ALL", list(c("catharina", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "catharina ziekenhuis",
  2, "ALL", list(c("maxima", "ziek.*|hosp.*|mc|medisch.*|cent.*")), NA, "maxima medisch centrum",
  2, "ALL", list(c("\\bamphia\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "amphia ziekenhuis",
  2, "ALL", list(c("medisch.*spectrum|\\bmst\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "medisch spectrum twente",
  2, "ALL", list(c("\\bzgt\\b|twente", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "ziekenhuisgroep twente",
  2, "ALL", list(c("\\btreant\\b", "zorggroep|ziek.*|hosp.*|mc|med.*|centrum")), NA, "treant zorggroep",
  2, "ALL", list(c("zuyderland")), NA, "zuyderland medisch centrum",
  2, "ALL", list(c("gelderse\\s*vallei", "ziek.*|hosp.*|mc|medisch|centrum")), NA, "ziekenhuis gelderse vallei",
  2, "ALL", list(c("antonius", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "st. antonius ziekenhuis",
  2, "ALL", list(c("albert\\s*schweitzer", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "albert schweitzer ziekenhuis",
  2, "ALL", list(c("\\bhaga\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "hagaziekenhuis",
  2, "ALL", list(c("reinier\\s*de\\s*graaf", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "reinier de graaf ziekenhuis",
  2, "ALL", list(c("haaglanden|\\bhmc\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "haaglanden medisch centrum",
  2, "ALL", list(c("\\bmeander\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "meander medisch centrum",
  2, "ALL", list(c("jeroen\\s*bosch", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "jeroen bosch ziekenhuis",
  2, "ALL", list(c("slingeland", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "slingeland ziekenhuis",
  2, "ALL", list(c("rivierenland", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "ziekenhuis rivierenland",
  2, "ALL", list(c("\\bzaans\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "zaans medisch centrum",
  2, "ALL", list(c("dijklander", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "dijklander ziekenhuis",
  2, "ALL", list(c("noordwest", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "noordwest ziekenhuisgroep",
  2, "ALL", list(c("\\bbravis\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "bravis ziekenhuis",
  2, "ALL", list(c("\\bgelre\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "gelre ziekenhuizen",
  2, "ALL", list(c("\\bflevo\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "flevoziekenhuis",
  2, "ALL", list(c("spaarne\\s*gasthuis", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "spaarne gasthuis",
  2, "ALL", list(c("viecuri", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "viecuri medisch centrum",
  2, "ALL", list(c("laurentius", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "laurentius ziekenhuis",
  2, "ALL", list(c("elkerliek", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "elkerliek ziekenhuis",
  2, "ALL", list(c("bernhoven", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "bernhoven",
  2, "ALL", list(c("franciscus|vlietland", "gasthuis|ziek.*|hosp.*|mc|med.*|centrum")), NA, "franciscus gasthuis & vlietland",
  2, "ALL", list(c("\\bikazia\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "ikazia ziekenhuis",
  2, "ALL", list(c("maasstad", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "maasstad ziekenhuis",
  2, "ALL", list(c("\\bbeatrix\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "beatrix ziekenhuis",
  2, "ALL", list(c("tergooi", "mc|med.*|centrum|ziek.*|hosp.*")), NA, "tergooi mc",
  2, "ALL", list(c("\\bdeventer\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "deventer ziekenhuis",
  2, "ALL", list(c("rijnstate", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "rijnstate",
  2, "ALL", list(c("jansdal", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "ziekenhuis st jansdal",
  2, "ALL", list(c("smellinghe", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "nij smellinghe",
  2, "ALL", list(c("martini", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "martini ziekenhuis",
  2, "ALL", list(c("ommelander", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "ommelander ziekenhuis groningen",
  2, "ALL", list(c("wilhelmina|\\bwza\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "wilhelmina ziekenhuis assen",
  2, "ALL", list(c("tjongerschans", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "ziekenhuis tjongerschans",
  2, "ALL", list(c("\\bst\\.?\\s*anna|sint\\s*anna", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "st. anna ziekenhuis",
  2, "ALL", list(c("saxenburgh|hardenberg", "mc|med.*|centrum|ziek.*|hosp.*")), NA, "saxenburgh medisch centrum",
  2, "ALL", list(c("koningin\\s*beatrix|\\bskb\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "streekziekenhuis koningin beatrix",
  2, "ALL", list(c("alrijne", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "alrijne ziekenhuis",
  2, "ALL", list(c("van\\s*weel\\s*-?\\s*bethesda", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "van weel-bethesda ziekenhuis",
  2, "ALL", list(c("maasziekenhuis|pantein", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "maasziekenhuis pantein",
  2, "ALL", list(c("canisius.*wilhelmina|\\bcwz\\b", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "canisius-wilhelmina ziekenhuis",
  2, "ALL", list(c("groene\\s*hart", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "groene hart ziekenhuis",
  2, "ALL", list(c("diakonessenhuis|diak", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "diakonessenhuis",
  2, "ALL", list(c("rode\\s*kruis", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "rode kruis ziekenhuis",
  2, "ALL", list(c("langeland", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "langeland ziekenhuis",
  2, "ALL", list(c("spijkenisse", "med.*|centrum|mc|ziek.*|hosp.*")), NA, "spijkenisse medisch centrum",
  2, "ALL", list(c("\\bolvg\\b|lieve\\s*vrouwe", "gasthuis|ziek.*|hosp.*|mc|med.*|centrum")), NA, "olvg",
  2, "ALL", list(c("st\\.?\\s*jans|sint\\s*jans", "gasthuis|ziek.*|hosp.*|mc|med.*|centrum")), NA, "st jans gasthuis (weert)",
  2, "ALL", list(c("zrt|rivas|gorinchem", "beatrix|ziek.*|hosp.*|mc|med.*|centrum")), NA, "beatrix ziekenhuis",
  2, "ALL", list(c("admir.*ruyter", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "admiraal de ruyter ziekenhuis",
  2, "ALL", list(c("tergooi|hilversum|blaricum", "mc|med.*|centrum|ziek.*|hosp.*")), NA, "tergooi mc",
  2, "ALL", list(c("noorderboog|sneek|antonius\\s*sneek", "ziek.*|hosp.*|mc|med.*|centrum")), NA, "antonius ziekenhuis sneek",
  2, "ALL", list(c("zaandam|zaans", "med.*|centrum|ziek.*|hosp.*")), NA, "zaans medisch centrum",
  2, "ALL", list(c("haarlem|hoofddorp", "spaarne|gasthuis|ziek.*|hosp.*|mc|med.*|centrum")), NA, "spaarne gasthuis",
  2, "ALL", list(c("dordrecht", "albert\\s*schweitzer|ziek.*|hosp.*")), NA, "albert schweitzer ziekenhuis",
  2, "ALL", list(c("harderwijk|lelystad", "jansdal|ziek.*|hosp.*|mc|med.*|centrum")), NA, "ziekenhuis st jansdal",
  2, "ALL", list(c("arnhem|velp|zevenaar", "rijnstate|ziek.*|hosp.*|mc|med.*|centrum")), NA, "rijnstate",
  2, "ALL", list(c("amersfoort", "meander|ziek.*|hosp.*|mc|med.*|centrum")), NA, "meander medisch centrum",
  2, "ALL", list(c("den\\s*haag|the\\s*hague", "haaglanden|haga|hmc|ziek.*|hosp.*|mc|med.*|centrum")), NA, "haaglanden/haga (check loc)",
  2, "ALL", list(c("den\\s*bosch|\\'s-?hertogenbosch", "jeroen\\s*bosch|ziek.*|hosp.*|mc|med.*|centrum")), NA, "jeroen bosch ziekenhuis",
  2, "ALL", list(c("apeldoorn|zutphen", "gelre|ziek.*|hosp.*|mc|med.*|centrum")), NA, "gelre ziekenhuizen",
  2, "ALL", list(c("breda|etten|leur", "amphia|ziek.*|hosp.*|mc|med.*|centrum")), NA, "amphia ziekenhuis",
  2, "ALL", list(c("eindhoven|veldhoven", "catharina|maxim|ziek.*|hosp.*|mc|med.*|centrum")), NA, "catharina/maxima (check loc)",
  2, "ALL", list(c("roosendaal|bergen\\s*op\\s*zoom", "bravis|ziek.*|hosp.*|mc|med.*|centrum")), NA, "bravis ziekenhuis",
  2, "ALL", list(c("almere", "flevo|ziek.*|hosp.*|mc|med.*|centrum")), NA, "flevoziekenhuis",
  2, "ALL", list(c("venlo|venray", "viecuri|ziek.*|hosp.*|mc|med.*|centrum")), NA, "viecuri medisch centrum",
  2, "ALL", list(c("roermond", "laurentius|ziek.*|hosp.*|mc|med.*|centrum")), NA, "laurentius ziekenhuis",
  2, "ALL", list(c("uden", "bernhoven|ziek.*|hosp.*|mc|med.*|centrum")), NA, "bernhoven",
  2, "ALL", list(c("rotterdam|schiedam", "franciscus|vlietland|maasstad|ikazia|ziek.*|hosp.*|mc|med.*|centrum")), NA, "franciscus/maasstad/ikazia (check loc)",
  2, "ALL", list(c("nijmegen", "radboud|cwz|canisius.*wilhelmina|ziek.*|hosp.*|mc|med.*|centrum")), NA, "radboudumc/cwz (check loc)",
  2, "ALL", list(c("ede", "gelderse\\s*vallei|ziek.*|hosp.*|mc|med.*|centrum")), NA, "ziekenhuis gelderse vallei",
  2, "ALL", list(c("delft", "reinier\\s*de\\s*graaf|ziek.*|hosp.*|mc|med.*|centrum")), NA, "reinier de graaf ziekenhuis",
  2, "ALL", list(c("alkmaar|den\\s*helder", "noordwest|ziek.*|hosp.*|mc|med.*|centrum")), NA, "noordwest ziekenhuisgroep",
  2, "ALL", list(c("hoorn|purmerend", "dijklander|ziek.*|hosp.*|mc|med.*|centrum")), NA, "dijklander ziekenhuis",
  2, "ALL", list(c("assen", "wilhelmina|wza|ziek.*|hosp.*|mc|med.*|centrum")), NA, "wilhelmina ziekenhuis assen",
  2, "ALL", list(c("enschede", "medisch.*spectrum|mst|ziek.*|hosp.*|mc|med.*|centrum")), NA, "medisch spectrum twente",
  2, "ALL", list(c("almelo|hengelo", "zgt|twente|ziek.*|hosp.*|mc|med.*|centrum")), NA, "ziekenhuisgroep twente",
  2, "ALL", list(c("elis.*", "twee|hosp.*")), NA, "elisabeth-tweesteden hospital",
  2, "ALL", list(c("\\bmira\\b", "ins.*")), NA, "mira institute for biological technology and technical medicine",
  2, "ALL", list(c("\\badelante\\b")), NA, "adelante",
  2, "ALL", list(c("alexander", "monro", "hosp.*|ziek.*")), NA, "alexander",
  2, "ALL", list(c("amalia", "child.*", "center|clin.*")), NA, "Amalia Kinderziekenhuis",
  2, "ALL", list(c("amalia", "kind.*|ziek.*")), NA, "Amalia Kinderziekenhuis",
  2, "ALL", list(c("mrc-holland")), NA, "mrc holland",
  2, "ALL", list(c("mrc","holland")), NA, "mrc holland",
  2, "ALL", list(c("aca.*","center", "epileptology")), NA, "academic center for epileptology kempenhaeghe",
  2, "ALL", list(c("aca.*","center", "dentistry", "ams.*")), NA, "academic centre for dentistry amsterdam",
  2, "ALL", list(c("ziek.*|hosp.*", "amstelland")), NA, "Ziekenhuis Amstelland",
  2, "ALL", list(c("zaan.*", "med.*")), NA, "zaans medical center",
  2, "ALL", list(c("yulius", "acad.*|ment.*|zorg")), NA, "yulius academy",
  2, "ALL", list(c("yili", "inno.*", "center|centre|ct")), NA, "yili innovation center europe",
  2, "ALL", list(c("wittenborg", "uni.*|hogeschool")), NA, "Wittenborg University",
  2, "ALL", list(c("wageningen", "inst.*", "marine")), NA, "wageningen institute for marine resources and ecosystem studies",
  2, "ALL", list(c("tinbergen", "inst.*")), NA, "tinbergen institute",
  # Hogescholen
  20, "ANY", list(c("saxion")),                                          NA,       "Saxion Hogeschool",
  21, "ANY", list(c("fontys")),                                          NA,       "Fontys Hogescholen",
  22, "ANY", list(c("hanze|hanzehogeschool")),                          NA,       "Hanze University of Applied Sciences",
  23, "ANY", list(c("hva|hogeschool van amsterdam")),                   NA,       "Hogeschool van Amsterdam",
  24, "ANY", list(c("hu|hogeschool utrecht")),                          NA,       "Hogeschool Utrecht",
  25, "ANY", list(c("inholland")),                                       NA,       "Hogeschool Inholland",
  26, "ANY", list(c("nhl stenden|nhl|stenden")),                        NA,       "NHL Stenden Hogeschool",
  27, "ANY", list(c("\\bavans\\b")),                                           NA,       "Avans Hogeschool",
  28, "ANY", list(c("windesheim")),                                      NA,       "Hogeschool Windesheim",
  29, "ANY", list(c("zuyd")),                                            NA,       "Zuyd Hogeschool",
  30, "ANY", list(c("hz|hz university of applied sciences|hogeschool zeeland")), NA, "HZ University of Applied Sciences",
  31, "ANY", list(c("han|hogeschool arnhem nijmegen|han university")),  NA,       "HAN University of Applied Sciences",
  32, "ANY", list(c("buas|breda university of applied sciences")),       NA,       "Breda University of Applied Sciences",
  33, "ANY", list(c("aeres")),                                           NA,       "Aeres Hogeschool",
  34, "ANY", list(c("haagse hogeschool|de haagse")),                     NA,       "De Haagse Hogeschool",
  34, "ALL", list(c("hague", "applied", "univ")),                     NA,       "De Haagse Hogeschool",
  35, "ALL", list(c("hogeschool","rotterdam")),                            NA,       "Hogeschool Rotterdam",
  36, "ALL", list(c("hogeschool|\\bhs\\b", "leiden")),                     NA,       "Hogeschool Leiden"
)
